/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegistrosRouteImport } from './routes/registros'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModalidadesSlugRouteImport } from './routes/modalidades.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalidadesSlugRoute = ModalidadesSlugRouteImport.update({
  id: '/modalidades/$slug',
  path: '/modalidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/hoje': typeof HojeRoute
  '/inicio': typeof InicioRoute
  '/registros': typeof RegistrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modalidades/$slug': typeof ModalidadesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/hoje': typeof HojeRoute
  '/inicio': typeof InicioRoute
  '/registros': typeof RegistrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modalidades/$slug': typeof ModalidadesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/hoje': typeof HojeRoute
  '/inicio': typeof InicioRoute
  '/registros': typeof RegistrosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modalidades/$slug': typeof ModalidadesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/hoje'
    | '/inicio'
    | '/registros'
    | '/sitemap.xml'
    | '/modalidades/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/hoje'
    | '/inicio'
    | '/registros'
    | '/sitemap.xml'
    | '/modalidades/$slug'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/hoje'
    | '/inicio'
    | '/registros'
    | '/sitemap.xml'
    | '/modalidades/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  HojeRoute: typeof HojeRoute
  InicioRoute: typeof InicioRoute
  RegistrosRoute: typeof RegistrosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ModalidadesSlugRoute: typeof ModalidadesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades/$slug': {
      id: '/modalidades/$slug'
      path: '/modalidades/$slug'
      fullPath: '/modalidades/$slug'
      preLoaderRoute: typeof ModalidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  HojeRoute: HojeRoute,
  InicioRoute: InicioRoute,
  RegistrosRoute: RegistrosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ModalidadesSlugRoute: ModalidadesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
